[theme]
primaryColor = "#6eb52f"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true